### dimensions
num_node_features: &F 3
num_nodes: &N 30
num_edges: &K 42
hidden_dim: &H 48


### hyperparameters
timestep_embedding: true
indicator_prediction: true

node_embedder:
    input_dim: *F
    layers: []
    output_dim: *H
    activation: "relu"

node_encoder:
    model_dim: *H
    num_heads: 3
    num_layers: 2
    gated: false
    activation: "silu"

cross_attention:
    model_dim: *H
    num_heads: 3
    num_layers: 3
    gated: false
    activation: "silu"

edge_mlp:
    input_dim: *H
    layers: [*H]
    output_dim: *H
    activation: "relu"

incidence_predictor:
    input_dim: *H
    layers: [64, 32, 16]
    output_dim: 1
    activation: "relu"

indicator_predictor:
    input_dim: *H
    layers: [32, 16]
    output_dim: 1
    activation: "relu"