### dimensions
num_node_features: &F 3
num_nodes: &N 30
num_edges: &K 42
hidden_dim: &H 48


### hyperparameters
timestep_embedding: true
indicator_prediction: true

node_encoder:
    input_dim: *F
    model_dim: *H
    num_heads: 4
    num_layers: 2
    activation: "silu"

cross_attention:
    input_dim: *H
    model_dim: *H
    num_heads: 4
    num_layers: 3
    activation: "silu"

incidence_predictor:
    input_dim: *H
    layers: [256, 256, 128]
    output_dim: *K
    activation: "silu"

indicator_predictor:
    input_dim: *H
    layers: [128, 64, 32]
    output_dim: 1
    activation: "silu"