name: hhrm

### dimensions
num_node_features: &F 3
num_edges: &K 42
hidden_dim: &H 36

### attention
timestep_embedding: true
time_dim: &T 8
freq_dim: 64

node_embedder:
    input_dim: *F # this gets overwritten in hhrm.py
    layers: []
    output_dim: *H
    activation: relu

node_CA_L:
    num_layers: 3
    embed_dim: *H
    context_dim: *T
    sa_config:
        num_heads: 3
        attn_type: flash 
    ca_config:
        num_heads: 3
        attn_type: flash 
    dense_config:
        hidden_layers: [72]
    # gated: false
    # scaling: true
    # activation: silu
    # ffn_factor: 2

edge_CA_H:
    num_layers: 5
    embed_dim: *H
    context_dim: *T
    sa_config:
        num_heads: 3
        attn_type: flash
    ca_config:
        num_heads: 3
        attn_type: flash
    # gated: false
    # scaling: true
    dense_config:
        hidden_layers: [72]

indicator_predictor:
    input_dim: *H
    layers: [64, 32]
    output_dim: 1
    activation: relu

hrm:
    iters_L: 3
    iters_H: 3
    segments: 4
    use_draft: false