name: mask2former

### dimensions
num_node_features: &F 3
num_edges: &K 42
hidden_dim: &H 36

### attention
timestep_embedding: false
time_dim: &T 8
freq_dim: 64
fourier_features: false

node_embedder:
    input_dim: *F # this gets overwritten in hhrm.py
    layers: []
    output_dim: *H
    activation: relu

node_CA_L:
    model_dim: *H
    c_dim: *T
    num_heads: 3
    num_layers: 3
    gated: false
    scaling: true
    activation: silu
    ffn_factor: 2

edge_CA_H:
    model_dim: *H
    c_dim: *T
    num_heads: 3
    num_layers: 5
    gated: false
    scaling: true
    activation: silu
    ffn_factor: 2

indicator_predictor:
    input_dim: *H
    layers: [64, 32]
    output_dim: 1
    activation: relu

# logit_offset: 0

hrm:
    iters_L: 1
    iters_H: 1
    segments: 1
    full_backprop: true
    use_draft: false
    persistent_A:
        masked_attention_frequency: layer # layer or segment
        masked_attention_threshold: 0.05