model: hhrm
dataset: convex_hull

optimizer: adam_atan2
scheduler: {
  "name": "cosine_warmup",
  "warmup_epochs": 10
}
learning_rate: 1.0e-4
num_epochs: 1000
num_workers: &W 2
nray: 8
seed: 123456
accelerator: 'cuda'
devices: [0]
dice_loss_coef: 0.5

dl_train:
  total_size: 20000
  batch_size: 64
  shuffle: true
  num_workers: *W

dl_val:
  total_size: 2000
  batch_size: 64
  shuffle: false
  num_workers: *W

dl_test:
  total_size: 2000
  batch_size: 64
  shuffle: false
  num_workers: *W