model: refiner
dataset: convex_hull

learning_rate: 3.0e-4
# learning_rate: 1.0e-3
num_epochs: 1000
num_workers: 4
nray: 0
seed: 123456
accelerator: 'cuda'
devices: [0]

dl_train:
  total_size: 20000
  batch_size: 64
  shuffle: true

dl_val:
  total_size: 2000
  batch_size: 64
  shuffle: false

dl_test:
  total_size: 2000
  batch_size: 64
  shuffle: false