model: refiner
dataset: particle_flow_jet

optimizer: adam
learning_rate: 3.0e-4
num_epochs: 200
num_workers: &W 6
nray: 8
seed: 123456
accelerator: 'cuda'
devices: [0]

dl_train:
  total_size: 200000
  batch_size: 64
  shuffle: true
  num_workers: *W

dl_val:
  total_size: 20000
  batch_size: 64
  shuffle: false
  num_workers: *W

dl_test:
  total_size: 20000
  batch_size: 64
  shuffle: false
  num_workers: *W